# -*- coding: utf-8 -*-
"""shredded_image_recovery_colour.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baLpHNXKXBIqC9kM75ljFow512CzS-GC

# Global Environment
"""

import numpy as np
from numpy import array
from numpy.random import permutation

import cv2
from google.colab.patches import cv2_imshow

import os
import shutil
import random
from random import shuffle
from math import sqrt
import re
import copy

root_path = '/content/drive/MyDrive/Colab Notebooks/Shredded Image Recovery/'

cifar10_dataset_path = root_path + 'cifar10 images/'
COCO_dataset_path = root_path + 'COCO dataset/val2017/'
sub_dir = root_path + 'Shredded Image Recovery colour/'

cwd = sub_dir + 'project/'
dataset_path = cwd + 'image_dataset/'

initial_weights_path = sub_dir + '2024102912.weights.h5'
save_weights_path = sub_dir + 'new.weights.h5'

#os.makedirs(cwd)

"""# General Utilities"""

def get_fraction(DIR, fraction, index):
    files = os.listdir(DIR)
    files.sort()
    #files = np.array(files)
    #np.random.shuffle(files)
    files = files[index*int(len(files)*fraction):(index+1)*int(len(files)*fraction)]
    return files

def get_n_files(DIR, number, start_index):
    files = os.listdir(DIR)
    files.sort()
    #files = np.array(files)
    #np.random.shuffle(files)
    files = files[start_index:start_index+number]
    return files

def resize_and_make_border(im, desired_size=100):
    old_size = im.shape[:2]  # old_size is in (height, width) format

    ratio = float(desired_size) / max(old_size)
    new_size = tuple([int(x * ratio) for x in old_size])

    # new_size should be in (width, height) format
    im = cv2.resize(im, (new_size[1], new_size[0]))

    delta_w = desired_size - im.shape[1]
    delta_h = desired_size - im.shape[0]
    top, bottom = delta_h // 2, delta_h - (delta_h // 2)
    left, right = delta_w // 2, delta_w - (delta_w // 2)

    new_im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=0)
    return np.reshape(new_im, (desired_size,desired_size,3))

def create_empty_directory(directory_path):
  if os.path.exists(directory_path):
    shutil.rmtree(directory_path)
  os.makedirs(directory_path)

def extract_pos_from_filenames(files):
    return [int(re.search('_(.+).jpg', filename).group(1)) for filename in files]

"""# Prepare Data"""

from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

def split_data_to_train_test(IM_DIR, data, train_path, test_path, test_size=0.2):
    data = [file for file in data if file[-3:] == 'jpg']
    print('total number of examples:', len(data))
    shuffle(data)
    test_files = data[:int(len(data) * test_size)]
    train_files = data[int(len(data) * test_size):]
    print('test set size:', len(test_files), ' train set size:', len(train_files))
    for file in train_files:
        shutil.copy(IM_DIR+file, train_path)
    for file in  test_files:
        shutil.copy2(IM_DIR+file, test_path)
    return train_files, test_files


def create_legit_combinations(path, files, tiles_per_dim, limit=10000):
    X = []
    # create images of legit combinations
    for f in files:
        if len(X) >= limit:
            break
        im = cv2.imread(path+f)
        height = im.shape[0]
        width = im.shape[1]
        frac_h = height//tiles_per_dim
        frac_w = width//tiles_per_dim
        for h in range(tiles_per_dim-1):
            for w in range(tiles_per_dim-1):
                crop1 = im[h*frac_h:(h+1)*frac_h, w*frac_w:(w+1)*frac_w, :]

                crop2 = im[(h + 1) * frac_h:(h + 2) * frac_h, w * frac_w:(w + 1) * frac_w, :]
                im1 = np.concatenate((crop1, crop2), axis=0)  # crop1 over crop2
                im1 = np.rot90(im1)
                crop2 = im[ h * frac_h:(h + 1) * frac_h, (w + 1) * frac_w:(w + 2) * frac_w, :]
                im2 = np.concatenate((crop1, crop2), axis=1)  # crop1 to the left of crop2
                # write the images to the "legit" directory
                X += [resize_and_make_border(im1)]
                X += [resize_and_make_border(im2)]
            # the last crop of every line
            crop1 = im[h * frac_h:(h + 1) * frac_h, (tiles_per_dim-1) * frac_w: tiles_per_dim * frac_w, :]
            crop2 = im[(h + 1) * frac_h:(h + 2) * frac_h, (tiles_per_dim-1) * frac_w: tiles_per_dim * frac_w, :]
            im1 = np.concatenate((crop1, crop2), axis=0)  # crop1 over crop2
            im1 = np.rot90(im1)
            X += [resize_and_make_border(im1)]
    return np.array(X)


def create_synthetic_combinations(path, files, tiles_per_dim, limit=40000):
    X = []
    # create images of NON-legit combinations
    for f in files:
        if len(X) >= limit:
            break
        im = cv2.imread(path + f)
        height = im.shape[0]
        width = im.shape[1]
        frac_h = height // tiles_per_dim
        frac_w = width // tiles_per_dim
        for j in range(tiles_per_dim - 1):
            crop1 = im[j * frac_h:(j + 1) * frac_h, j * frac_w:(j + 1) * frac_w, :]
            for k in range(j + 1, tiles_per_dim):
                crop2 = im[k * frac_h:(k + 1) * frac_h, k * frac_w:(k + 1) * frac_w, :]
                if crop1.shape != crop2.shape:  # make sure both crops are of same size
                    break
                im1 = np.concatenate((crop1, crop2), axis=1)  # crop1 to the left of crop2
                X += [resize_and_make_border(im1)]

                im2 = np.concatenate((crop1, crop2), axis=0)  # crop1 over crop2
                im2 = np.rot90(im2)
                X += [resize_and_make_border(im2)]

                im3 = np.concatenate((crop2, crop1), axis=1)  # crop2 to the left of crop1
                X += [resize_and_make_border(im3)]

                im4 = np.concatenate((crop2, crop1), axis=0)  # crop2 over crop1
                im4 = np.rot90(im4)
                X += [resize_and_make_border(im4)]
    return np.array(X)


def prepare(IM_DIR, tiles_per_dim = 4):
    #files = os.listdir(IM_DIR)
    #files = get_n_files(IM_DIR, 1000, 0)
    #print(files)

    #os.makedirs(dataset_path)
    train_path = dataset_path + 'train/'
    test_path = dataset_path + 'test/'
    #os.makedirs(test_path)
    #os.makedirs(train_path)

    #train_files, test_files = split_data_to_train_test(IM_DIR, files, train_path, test_path, 0.2)
    train_files = os.listdir(train_path)
    test_files = os.listdir(test_path)
    X1 = create_legit_combinations(train_path, train_files, tiles_per_dim)
    y1 = np.ones((X1.shape[0]))
    X2 = create_synthetic_combinations(train_path, train_files, tiles_per_dim)
    y2 = np.zeros((X2.shape[0]))
    print('X1 shape ',X1.shape)
    print('y1 shape ',y1.shape)
    print('X2 shape ',X2.shape)
    print('y2 shape ',y2.shape)

    X = np.concatenate((X1,X2))
    y = np.concatenate((y1,y2))
    y = to_categorical(y, num_classes=2)
    print('X shape ',X.shape)
    print('y shape ',y.shape)

    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y, shuffle=True)

    np.save(dataset_path+'X_train', X_train)
    np.save(dataset_path+'X_val', X_val)
    np.save(dataset_path+'y_train', y_train)
    np.save(dataset_path+'y_val', y_val)


#prepare(cifar10_dataset_path, tiles_per_dim = 4)
prepare(COCO_dataset_path, tiles_per_dim = 4)

X_train = np.load(cwd + 'image_dataset/X_train.npy')
X_val   = np.load(cwd + 'image_dataset/X_val.npy')
y_train = np.load(cwd + 'image_dataset/y_train.npy')
y_val   = np.load(cwd + 'image_dataset/y_val.npy')

for i in range(3):
    print('Image X[',i,']')
    cv2_imshow(X_train[i])
    print('label=',str(y_train[i]),'  ', str(X_train[i].shape))

for i in range(3):
    print('Image X[',i,']')
    cv2_imshow(X_val[i])
    print('label=',str(y_val[i]),'  ', str(X_val[i].shape))

"""# legit_img_model"""

# from __future__ import print_function
import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
from keras import optimizers
from keras import regularizers


class Network:
    def __init__(self):
        self.weight_decay = 0.0005
        self.x_shape = [100, 100, 3]  # Resized all examples to this size

        self.model = self.build_model()
        self.model.load_weights(initial_weights_path)

    def build_model(self):
        model = Sequential()
        weight_decay = self.weight_decay

        model.add(Conv2D(64, (3, 3), padding='same', input_shape=self.x_shape, kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())
        model.add(Dropout(0.3))

        model.add(Conv2D(64, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())

        model.add(MaxPooling2D(pool_size=(2, 2)))

        model.add(Conv2D(128, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())
        model.add(Dropout(0.4))

        model.add(Conv2D(128, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())

        model.add(MaxPooling2D(pool_size=(2, 2)))

        model.add(Conv2D(256, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())
        model.add(Dropout(0.4))

        model.add(Conv2D(256, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())
        model.add(Dropout(0.4))

        model.add(Conv2D(256, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())

        model.add(MaxPooling2D(pool_size=(3, 3)))

        model.add(Dropout(0.5))

        model.add(Flatten())
        model.add(Dense(32, kernel_regularizer=regularizers.l2(weight_decay)))
        model.add(Activation('relu'))
        model.add(BatchNormalization())

        model.add(Dropout(0.4))
        model.add(Dense(2))
        model.add(Activation('softmax'))
        return model

    def predict(self, X):
        return self.model.predict(X)

    def fit2(self, X, y, X_val=None, y_val=None):
        # training parameters
        batch_size = 256
        maxepoches = 10
        learning_rate = 0.1
        lr_decay = 1e-6
        lr_drop = 10

        def lr_scheduler(epoch):
            return learning_rate * (0.5 ** (epoch // lr_drop))

        reduce_lr = keras.callbacks.LearningRateScheduler(lr_scheduler)

        # optimization details
        sgd = optimizers.SGD(learning_rate=learning_rate, momentum=0.9, nesterov=True)
        self.model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

        self.model.fit(X, y, validation_data=(X_val, y_val), epochs=maxepoches,
                       batch_size=batch_size, shuffle=True, callbacks=[reduce_lr], verbose=1)

    def fit(self, X, y, X_val=None, y_val=None):
        # training parameters
        batch_size = 64
        maxepoches = 10
        learning_rate = 0.001
        #lr_decay = 1e-6
        lr_drop = 10

        def lr_scheduler(epoch):
            self.model.save_weights(save_weights_path)
            return learning_rate * (0.5 ** (epoch // lr_drop))

        reduce_lr = keras.callbacks.LearningRateScheduler(lr_scheduler)

        # optimization details
        sgd = optimizers.SGD(learning_rate=learning_rate, momentum=0.9, nesterov=True)
        self.model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

        # data augmentation
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            width_shift_range=0,  # randomly shift images horizontally (fraction of total width)
            height_shift_range=0,  # randomly shift images vertically (fraction of total height)
            horizontal_flip=True,  # randomly flip images
            vertical_flip=True)  # randomly flip images
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(X)

        historytemp = self.model.fit(datagen.flow(X, y, batch_size=batch_size),
                                               steps_per_epoch=X.shape[0] // batch_size,
                                               epochs=maxepoches,
                                               validation_data=(X_val, y_val), callbacks=[reduce_lr], verbose=1)

    def summary(self):
        self.model.summary()


network = Network()
network.summary()

def do_training(network):
    X_train = np.load(dataset_path+'X_train.npy')
    X_val = np.load(dataset_path+'X_val.npy')
    y_train = np.load(dataset_path+'y_train.npy')
    y_val = np.load(dataset_path+'y_val.npy')

    network.fit2(X_train, y_train, X_val, y_val)
    network.model.save_weights(save_weights_path)

do_training(network)

"""# evaluate_aux"""

#from legit_img_model import Network

def show_row(images, row):  # for debugging
    row_image = np.concatenate([images[i] for i in row], axis=1)  # concatenate images in row to make a single image
    cv2.imshow('row image', row_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return row_image

def get_row_image(images, row):  # for debugging
    row_image = np.concatenate([images[i] for i in row], axis=1)  # concatenate images in row to make a single image
    return row_image


def apply_transform(img):
    return resize_and_make_border(img, 100)


def get_pair_probs(images, clf, is_image=True):
    # returns a matrix (2darray) containing the probabilities for concatenating crops
    # index (i,j) contains the probability that concat'ing images[i],images[j] (in that order) will yield a legit image
    t = len(images)

    concats = []
    indices = []
    pairs = [(i,j) for i in range(t) for j in range(t) if i!=j]
    for (ind1, ind2) in pairs:
        im1 = images[ind1]
        im2 = images[ind2]
        concat = np.concatenate((im1, im2), axis=1)  # im1 to the left of im2
        concat = apply_transform(concat)

        concats += [concat]
        indices += [(ind1,ind2)]
    concats = np.array(concats)

    preds = clf.predict(concats)[:,1]
    probs = np.zeros((t,t))
    for i in range(len(indices)):
        probs[indices[i]] = preds[i]
    return probs


def make_rows(images, clf, is_image=True):
    # builds row by row, using the probabilities for concat'ing each pair
    probs = get_pair_probs(images, clf, is_image)
    t = int(sqrt(len(images)))
    rows = []
    pool = list(range(t**2))
    row = [0]   # maybe better start from random
    pool.remove(0)
    # row_imgs = []
    while len(pool)>0:
        left_nominees = [(nominee, probs[nominee, row[0]]) for nominee in pool]
        right_nominees = [(nominee, probs[row[-1], nominee]) for nominee in pool]
        best_left, left_score = max(left_nominees, key=lambda x: x[1])
        best_right, right_score = max(right_nominees, key=lambda x: x[1])
        if left_score > right_score:
            probs[:, row[0]] = -1
            row.insert(0, best_left)
            pool.remove(best_left)
            probs[best_left, :] = -1  # set probability ((for best_left to be on the left of something)) to -1, so not to choose again
        else:
            probs[row[-1], :] = -1
            row.append(best_right)
            pool.remove(best_right)
            probs[:, best_right] = -1  # set probability ((for best_right to be on the right of something)) to -1, so not to choose again

        if len(row) == t:  # if we are done building this row
            probs[row[-1], :] = -1  # the rightmost crop can't be chosen again for other row
            probs[:,row[0]] = -1    # same for leftmost
            # row_imgs += [show_row(images, row)]
            # if len(rows) == t-1:
            #     row_imgs = np.concatenate([row_imgs[i] for i in range(t)],axis=0)  # concatenate images in row to make a single image
            #     cv2.imshow('rows', cv2.resize(row_imgs, (0,0), fx=0.35, fy=0.35))
            #     cv2.waitKey(0)
            #     cv2.destroyAllWindows()
            rows += [row]
            if len(pool) > 0:
                row = [pool[0]]  # take an unused crop and start building a new row
                pool.remove(pool[0])

    return rows


def two_rows_score(images, row1, row2, clf, is_image=True):
    merged_images = [ apply_transform(np.rot90(np.concatenate([images[row1[i]], images[row2[i]]], axis=0)))
                          for i in range(len(row1)) ]

    preds = clf.predict(np.array(merged_images))[:, 1]
    return sum(preds)


def solve_image(images):
    clf = Network()
    rows = make_rows(images, clf)
    pairs = [(i, j) for i in range(len(rows)) for j in range(len(rows)) if i != j]
    row_probs = np.zeros((len(rows), len(rows)))
    for (i,j) in pairs:
        row_probs[(i,j)] = two_rows_score(images, rows[i], rows[j], clf)

    pool = list(range(len(rows)))
    cur_rows = [0]  # maybe better start from random
    pool.remove(0)
    while len(pool) > 0:
        up_nominees = [(nominee, row_probs[nominee,cur_rows[0]]) for nominee in pool]
        down_nominees = [(nominee, row_probs[cur_rows[-1], nominee]) for nominee in pool]
        # up_score = np.max(row_probs[:, cur_rows[0]])
        # down_score = np.max(row_probs[cur_rows[-1], :])
        best_up, up_score = max(up_nominees, key=lambda x: x[1])
        best_down, down_score = max(down_nominees, key=lambda x: x[1])
        if up_score > down_score:
            # best_up = np.argmax(row_probs[:, cur_rows[0]])
            row_probs[:, cur_rows[0]] = -1
            row_probs[best_up, :] = -1
            cur_rows.insert(0, best_up)
            pool.remove(best_up)
        else:
            # best_down = np.argmax(row_probs[cur_rows[-1], :])
            row_probs[cur_rows[-1], :] = -1
            row_probs[:, best_down] = -1
            cur_rows.append(best_down)
            pool.remove(best_down)

        if len(cur_rows) == len(rows):  # if we are done building the whole image
            labels = []
            for row_index in cur_rows:
                labels.extend(rows[row_index])
            # code for showing final built image
            img = np.concatenate([get_row_image(images, rows[row_ind]) for row_ind in cur_rows], axis=0)
            cv2_imshow(img)
            # cv2.waitKey(5000)
            # cv2.destroyAllWindows()
            ###
            # img = np.concatenate([get_row_image(images, rw) for rw in [list(range(0,4)),list(range(4,8)),list(range(8,12)),list(range(12,16))]], axis=0)
            # cv2.imshow('original', img)
            # cv2.waitKey(5000)

    actual_labels = [x[0] for x in sorted(enumerate(labels), key=lambda a: a[1])]  # to match the input: for image[i] the label is labels[i]
    # print('predicted labels=', actual_labels)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()
    return actual_labels

"""# evaluate"""

#from evaluate_aux import solve_image


def predict(images):
    return solve_image(images)

def evaluate(file_dir='example/'):
    files = os.listdir(file_dir)
    files.sort()
    images = []
    for f in files:
        im = cv2.imread(file_dir + f)
        im = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
        images.append(im)

    Y = predict(images)
    return Y


def test_image(file_dir='example/'):
    files = os.listdir(file_dir)
    #files.sort()
    shuffle(files)
    print(files)
    images = []
    for f in files:
        im = cv2.imread(file_dir + f)
        images.append(im)

    actual = extract_pos_from_filenames(files)
    perm = list(permutation(range(len(images))))
    # print('perm=', [actual[perm[i]] for i in range(len(images))])
    permutated_images = []
    for i in range(len(images)):
        permutated_images.append(images[perm[i]])
        # cv2.imshow('title',images[perm[i]])
        # print((images[perm[i]]).shape)
        # cv2.waitKey(0)
        # cv2.destroyAllWindows()

    Y = predict(permutated_images)
    accuracy = 100*(sum([Y[i]==actual[perm[i]] for i in range(len(images))])/len(images))
    # print('0-1 Accuracy =', accuracy, '%')
    return accuracy


# test_image()

"""# Test Images"""

#from evaluate import test_image

OUTPUT_DIR = '/content/drive/MyDrive/Colab Notebooks/Shredded Image Recovery/Shredded Image Recovery active 2/project/test_images/'
output_2x2_path = OUTPUT_DIR + '2x2/'
output_3x3_path = OUTPUT_DIR + '3x3/'
output_4x4_path = OUTPUT_DIR + '4x4/'
output_5x5_path = OUTPUT_DIR + '5x5/'

def make_shreds(IM_DIR, image_file, tiles_per_dim, folder_index, output_path):
    os.makedirs(output_path+str(folder_index))
    im = cv2.imread(IM_DIR + image_file)
    height = im.shape[0]
    width = im.shape[1]
    frac_h = height // tiles_per_dim
    frac_w = width // tiles_per_dim
    i = 0
    for h in range(tiles_per_dim):
        for w in range(tiles_per_dim):
            crop = im[h * frac_h:(h + 1) * frac_h, w * frac_w:(w + 1) * frac_w]
            cv2.imwrite(output_path + str(folder_index) + '/' + image_file[:-4] + "_{}.jpg".format(i), crop)
            i = i + 1


def prepare_images_crops(IM_DIR = cwd + 'image_dataset/test/' , num_of_examples_per_t = 10):
    create_empty_directory(OUTPUT_DIR)
    os.makedirs(output_2x2_path)
    os.makedirs(output_3x3_path)
    os.makedirs(output_4x4_path)
    os.makedirs(output_5x5_path)

    files = os.listdir(IM_DIR)
    shuffle(files)

    i = 0
    for f in files[:num_of_examples_per_t]:
        i += 1
        make_shreds(IM_DIR, f, 2, i, output_2x2_path)

    i = 0
    for f in files[:num_of_examples_per_t]:
        i += 1
        make_shreds(IM_DIR, f, 3, i, output_3x3_path)

    i = 0
    for f in files[:num_of_examples_per_t]:
        i += 1
        make_shreds(IM_DIR, f, 4, i, output_4x4_path)

    i = 0
    for f in files[:num_of_examples_per_t]:
        i += 1
        make_shreds(IM_DIR, f, 5, i, output_5x5_path)


def test():

    print('\n***Testing 2x2 images***')
    image_folders = os.listdir(output_2x2_path)
    image_folders = image_folders[:5]
    total_acc = 0
    for image_folder in image_folders:
        acc = test_image(output_2x2_path+image_folder+'/')
        total_acc += acc
        print('image#'+image_folder,'0-1 Accuracy =', acc, '%')
    print('***', '2x2 images total accuracy =', total_acc / len(image_folders), '***')

    print('\n***Testing 3x3 images***')
    image_folders = os.listdir(output_3x3_path)
    image_folders = image_folders[:5]
    total_acc = 0
    for image_folder in image_folders:
        acc = test_image(output_3x3_path+image_folder+'/')
        total_acc += acc
        print('image#'+image_folder,'0-1 Accuracy =', acc, '%')
    print('***', '3x3 images total accuracy =', total_acc / len(image_folders), '***')

    print('\n***Testing 4x4 images***')
    image_folders = os.listdir(output_4x4_path)
    image_folders = image_folders[:5]
    total_acc = 0
    for image_folder in image_folders:
        acc = test_image(output_4x4_path+image_folder+'/')
        total_acc += acc
        print('image#'+image_folder,'0-1 Accuracy =', acc, '%')
    print('***', '4x4 images total accuracy =', total_acc / len(image_folders), '***')

    print('\n***Testing 5x5 images***')
    image_folders = os.listdir(output_5x5_path)
    image_folders = image_folders[:5]
    total_acc = 0
    for image_folder in image_folders:
        acc = test_image(output_5x5_path+image_folder+'/')
        total_acc += acc
        print('image#'+image_folder,'0-1 Accuracy =', acc, '%')
    print('***', '5x5 images total accuracy =', total_acc / len(image_folders), '***')

#prepare_images_crops(cwd + 'image_dataset/test/', 10)
test()